---------------------------------------
--	itms_manager
--
-- by Alundaio
---------------------------------
--[[
Copyright (C) 2012 Alundaio
This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License-]]
--]]

-- =======================================================================================
-- Modified by Tronex
-- 2018/7/18 - Added support for new usable items (maps,craft)
-- 2018/7/21 - Added the ability to gather/separate muti-use items
-- =======================================================================================


local ini = ini_file("plugins\\itms_manager.ltx")
local ini_med = ini_file("misc\\items\\item_management\\med_packs.ltx")

--Backpack stash mod
local BackPackStashEnable = ini:r_bool_ex("backpack_stash","enable",false)
local BackPackStashAllowInBase = BackPackStashEnable and ini:r_bool_ex("backpack_stash","allow_in_base",false)
local BackPackStashSpot = BackPackStashEnable and ini:r_string_ex("backpack_stash","map_spot") or "treasure" 
local BackPackStashEnableTip = BackPackStashEnable and ini:r_bool_ex("backpack_stash","enable_news_tip",false)
local BackPackStashEnableUi = BackPackStashEnable and ini:r_bool_ex("backpack_stash","enable_ui",false)

-- Sleep bag mod
local SleepBagEnable = ini:r_bool_ex("sleeping_bag","enable",true)
local SleepBagRadius = SleepBagEnable and ini:r_float_ex("sleeping_bag","unsafe_radius") or 5000
local SleepBagPlaceable = SleepBagEnable and ini:r_bool_ex("sleeping_bag","use_placeable",false)
local SleepBagGameStart = SleepBagEnable and ini:r_bool_ex("sleeping_bag","have_at_start",false)
local SleepBagSections = SleepBagEnable and alun_utils.collect_section(ini,"sleeping_bag_sections",true)
local SleepBagPlaceableSections = SleepBagEnable and alun_utils.collect_section(ini,"sleeping_bag_ph_sections",true)

-- Actor backpack mod
local ActorBackPackEnable = ini:r_bool_ex("actor_backpack","enable",false)
local ActorBackPackSpot = ActorBackPackEnable and ini:r_string_ex("actor_backpack","map_spot") or "treasure"
local ActorBackPackSlot = ActorBackPackEnable and ini:r_string_ex("actor_backpack","quick_slot") or "slot_3"
local ActorBackPackKeep = ActorBackPackEnable and alun_utils.collect_section(ini,"actor_backpack_keep_items",true)
local ActorBackPackForced = ActorBackPackEnable and ini:r_bool_ex("actor_backpack","actor_backpack_always_have",false)

-- Repair mod
local RepairModEnable = ini:r_bool_ex("repair_mod","enable",true)
local RepairTools = RepairModEnable and alun_utils.collect_section(ini,"repair_mod_tools",true)
local RepairUI = RepairModEnable and ini:r_bool_ex("repair_mod","use_ui",false)

-- Loot Mutant mod
local MutantLootEnable = ini:r_bool_ex("mutant_loot_mod","enable",true)
local MutantLootEnableUI = ini:r_bool_ex("mutant_loot_mod","enable_ui",false)
local MutantLootDecayTime = ini:r_float_ex("mutant_loot_mod","decay_time") or 7200

-- Cooking mod
local CookingModEnable = ini:r_bool_ex("cooking_mod","enable")
local CookingTools = CookingModEnable and alun_utils.collect_section(ini,"cooking_mod_tools",true)

-- Condition checker mod
local ConditionCheckerModEnable = alun_utils.read_from_ini(ini_file("plugins\\condition_checker.ltx"),"con_checker_mod","enable","bool",true)
local ConditionCheckerTools = ConditionCheckerModEnable and alun_utils.collect_section(ini_file("plugins\\condition_checker.ltx"),"con_checker_mod_tools",true)
-- Campfire Cooking
local CampCookingTools = alun_utils.collect_section(ini,"camp_cooking_tool",true)

-- Flashlight mod
local FlashlightModEnable = ini:r_bool_ex("flashlight_mod","enable",false)
local FlashlightSections = FlashlightModEnable and alun_utils.collect_section(ini,"flashlight_sections",true)
local FlashlightFar = false

-- Static Message
ShowMessage = nil
ShowMessageInit = nil
ShowMessageTime = nil

TorchType = 0
local torch_delay
local actor_fill_backpack
local clsid_to_section = {
	--> TRX A-Life Revamp
	[clsid.psysucker_s]		= "psysucker",
	[clsid.lurker_s]		= "lurker",
	[clsid.karlik_s]		= "karlik",
	
	[clsid.bloodsucker_s] 	= "bloodsucker",
	[clsid.boar_s] 			= "boar",
	[clsid.burer_s] 		= "burer",
	[clsid.chimera_s]		= "chimera",
	[clsid.controller_s]	= "controller",
	[clsid.dog_s]			= "dog",
	[clsid.flesh_s]			= "flesh",
	[clsid.gigant_s]		= "gigant",
	[clsid.poltergeist_s]	= "poltergeist",
	[clsid.psy_dog_s]		= "psy_dog",
	[clsid.psy_dog_phantom_s] = "psy_dog",
	[clsid.pseudodog_s]		= "pseudodog",
	[clsid.snork_s]			= "snork",
	[clsid.tushkano_s]		= "tushkano",
	[clsid.cat_s]			= "cat",
	[clsid.fracture_s]		= "fracture",
	[clsid.zombie_s]		= "zombie",
	[clsid.crow]			= "crow",
	[clsid.rat_s]			= "rat"
}


--=======================================< Callbacks >=======================================--

function on_game_start()
	RegisterScriptCallback("on_game_load",on_game_load)
	RegisterScriptCallback("actor_on_update",actor_on_update)
	RegisterScriptCallback("actor_on_item_drop",actor_on_item_drop)
	RegisterScriptCallback("monster_on_actor_use_callback",monster_on_actor_use_callback)
	RegisterScriptCallback("actor_on_item_use",actor_on_item_use)
	RegisterScriptCallback("actor_on_item_take",actor_on_item_take)
	RegisterScriptCallback("actor_on_item_take_from_box",actor_on_item_take_from_box)
	RegisterScriptCallback("physic_object_on_use_callback",physic_object_on_use_callback)
	RegisterScriptCallback("on_key_press",on_key_press)
	RegisterScriptCallback("CUIActorMenu_OnItemDropped",on_item_drag_dropped)
	--RegisterScriptCallback("CUIActorMenu_OnItemFocusReceive",on_item_focus)
end

function on_game_load()


	if (ActorBackPackEnable and ActorBackPackForced) then
		local actor_itm_backpack_id= utils.load_var(db.actor,"actor_itm_backpack_id",nil)
		local actor_inv_backpack_id = utils.load_var(db.actor,"actor_inv_backpack_id",nil)
		if (not actor_itm_backpack_id and not actor_inv_backpack_id) then
			get_console():execute(ActorBackPackSlot.." itm_actor_backpack")
			local se_obj = alife():create("itm_actor_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),0)
			if (se_obj) then
				utils.save_var(db.actor,"actor_itm_backpack_id",se_obj.id)
			end
		end
	end

	--[[
	if (SleepBagEnable and SleepBagGameStart) then
		local sleepbag_id = utils.load_var(db.actor,"itm_sleepbag_id",nil)
		if (not sleepbag_id) then
			local se_obj = alife():create("itm_sleepbag",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),0)
			utils.save_var(db.actor,"itm_sleepbag_id",se_obj.id)
		end
	end
	--]]
end

function actor_on_update()

	if not has_alife_info("start_equipement_damaged") then
		xr_effects.damage_actor_items()
		--wild territory
		local sec = "itm_repairkit_tier_1"
		local pos = vector()
			pos.x = -214.39
			pos.y = 3.40
			pos.z = 102.27
		local gv_id = 1880
		local lv_id = 22625
		alife():create(sec,pos,lv_id,gv_id)
		--red forest
		sec = "itm_repairkit_tier_2"
		pos.x = -139.86
		pos.y = -6.19
		pos.z = -64.10
		gv_id = 2772
		lv_id = 6166
		alife():create(sec,pos,lv_id,gv_id)
		--agro underground
		sec = "itm_repairkit_tier_3"
		pos.x = 117.16
		pos.y = -7.06
		pos.z = -58.85
		gv_id = 3616
		lv_id = 230
		alife():create(sec,pos,lv_id,gv_id)
		
		give_info("start_equipement_damaged")
	end

	check_actor_backpack()

	if (FlashlightModEnable) then
		local obj = db.actor:active_detector()
		local torch = db.actor:object("device_torch")
		if (obj and FlashlightSections[obj:section()]) then
			if (has_alife_info("enable_device_torch")) then
				db.actor:disable_info_portion("enable_device_torch")
				alife():create("device_torch_dummy",db.actor:position(),0,0,0)
				SetHudMsg(game.translate_string("st_lamp_disconnected"),5)
			end

			if not (torch) then
				alife():create("device_torch",db.actor:position(),0,0,0)
			end

			if (FlashlightFar) then
				TorchType = 1
			else
				TorchType = 2
			end
			
			if (torch and not torch:torch_enabled()) then
				if not (torch_delay) then
					torch_delay = time_global() + 1000
				end

				if (time_global() > torch_delay) then
					torch:enable_torch(true)
				end
			end
		else
			if (torch and not has_alife_info("enable_device_torch")) then
				TorchType = 0
				FlashlightFar = false;
				if (torch:torch_enabled()) then
					torch:enable_torch(false)
					torch_delay = nil
				end
			end
		end
	end
end

function actor_on_item_drop(obj) -- bind_stalker on_item_drop
	if not (obj) then
		return
	end
	if (ActorBackPackEnable and ActorBackPackForced and obj:section() == "itm_actor_backpack") then
		local se_itm = alife():create("itm_actor_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())

		if not (se_itm) then
			return
		end

		utils.save_var(db.actor,"actor_itm_backpack_id",se_itm.id)
		alife():release( alife():object(obj:id()) )
	end
	
	if (db.actor:has_info("actor_made_wish_for_riches")) then 
		db.actor:transfer_item(obj,db.actor)
	end
end

function monster_on_actor_use_callback(obj,who) --// Faustle
	if not (MutantLootEnable) then
		return
	end

	local looted = utils.se_obj_load_var(obj:id(),obj:name(),"looted")
	if (looted) then
		return
	end

	if (obj:clsid() == clsid.crow) then
		utils.save_var(obj, "looted", true)
	else
		utils.se_obj_save_var(obj:id(),obj:name(),"looted",true)
	end

	xr_corpse_detection.set_valuable_loot(obj:id(),false)

	local st = db.storage[obj:id()]
	if (st and st.death_time and game.get_game_time():diffSec(st.death_time) > MutantLootDecayTime) then
		SetHudMsg(game.translate_string("st_body_decayed"),4)
	else
		local hud = get_hud()
		if (hud) then
			ui_mutant_loot.loot_ui(hud,obj,obj:id(),obj:section(),obj:clsid())
		end
	end
end

function actor_on_item_use(obj) -- bind_stalker on_item_use
	if (db.actor:has_info("actor_made_wish_for_riches")) then
		return 
	end

	-- Backpack
	if (BackPackStashEnable and obj:section() == "itm_backpack") then

		if (BackPackStashAllowInBase ~= true) then
			local in_base
			local zone
			local t = {"zat_a2_sr_no_assault","jup_a6_sr_no_assault","jup_b41_sr_no_assault"}
			for i=1,#t do
				zone = db.zone_by_name[t[i]]
				if (zone and zone:inside(db.actor:position())) then
					in_base = true
					break
				end
			end

			if (in_base) then
				SetHudMsg(game.translate_string("st_stash_unsafe"),4)
				alife():create("itm_backpack",db.actor:position(),0,0,0)
				return
			end
		end

		local se_obj = alife():create("inv_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
		if (se_obj) then
			local level_name = level.name()

			if not (BackPackStashEnableUi) then
				local count = utils.load_var(db.actor, level_name.."bpk_count", 0)
				utils.save_var(db.actor, level_name.."bpk_count", count+1)
				level.map_add_object_spot_ser(se_obj.id, BackPackStashSpot, level_name.." stash "..count+1)
			else
				local hud = get_hud()
				if (hud) then
					hud:HideActorMenu()
					local ui = ui_itm_backpack and ui_itm_backpack.backpack_ui(hud,se_obj.id,BackPackStashSpot)
					if (ui) then
						ui:ShowDialog(true)
					end
				end
			end

			if (BackPackStashEnableTip) then
				SetHudMsg(game.translate_string("st_stash_created"),4)
			end
		end
		return
	end

	-- Sleeping bag
	if (SleepBagEnable and SleepBagSections[obj:section()]) then
		local sec = obj:section()
		if (SleepBagPlaceable) then
			local ph_sec = system_ini():r_string_ex(sec,"placeable_section")
			local se_obj = alife():create(ph_sec or "ph_sleepbag",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
			local compr = alife():create("compression_bag",db.actor:position(),0,0,0)
		else
			local se_obj = alife():create(sec,db.actor:position(),0,0,0)
			local hud = get_hud()
			if (hud) then
				hud:HideActorMenu()
			end
			local ui = ui_sleep_dialog.sleep_bag(se_obj,sec)
		end
		return
	end
	
	if (obj:section() == "compression_bag") then
	-- Compression bag
		for i=1,65535 do
			local s = alife():object(i)
			if s then
				local o = level.object_by_id(s.id)
				if o  then
					local slbag = o:section()
					if slbag == "ph_sleepbag" and o:position():distance_to(db.actor:position()) < 1 then
						alife():create("itm_sleepbag",db.actor:position(),0,0,0)
						alife():release(s)
						alife():release(alife():object(obj:id()))
						actor_effects.use_item("itm_sleepbag")
						break
					end
				end
			end
		end
	end

	-- Actor backpack
	if (ActorBackPackEnable and obj:section() == "itm_actor_backpack") then
		local id = ActorBackPackForced and utils.load_var(db.actor,"actor_inv_backpack_id",nil)
		if (id) then
			SetHudMsg(game.translate_string("st_stash_placed"),4)
			alife():create("itm_actor_backpack",db.actor:position(),0,0,0)
			return
		end

		local se_obj = alife():create("inv_actor_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())

		level.map_add_object_spot_ser(se_obj.id, ActorBackPackSpot,"–юкзак сталкера "..db.actor:character_name())

		utils.save_var(db.actor,"actor_inv_backpack_id",se_obj.id)
	end

	-- Repair mod
	if (RepairModEnable and RepairTools[obj:section()]) then
	--	if (RepairUI) then --? wafel don't know yet
		local hud = get_hud()
		if (hud) then
			hud:HideActorMenu()
			local ui = ui_itm_repair and ui_itm_repair.repair_ui(hud,obj,obj:section())
			if (ui) then
				ui:ShowDialog(true)
				--ui:FillList()
			end
		end
	end
	
	-- Cooking mod
	if (CookingModEnable and CookingTools[obj:section()]) then
		local hud = get_hud()
		hud:HideActorMenu()
		local ui = ui_itm_cooking and ui_itm_cooking.cooking_ui(hud,obj:section())
		if (ui) then
			ui:ShowDialog(true)
			ui:FillList()
		end
	end
	
	if (obj:section() == "army_bowler") then
		if (CookingModEnable and CampCookingTools[obj:section()] and campfire_cook()) then
			local hud = get_hud()
			--hud:HideActorMenu()
			local ui = ui_itm_camp_cooking and ui_itm_camp_cooking.cooking_ui(hud,obj:section())
			if (ui) then
				ui:ShowDialog(true)	
				ui:FillPartsList()
			end
		else
			alife():create("army_bowler",db.actor:position(),0,0,0)
			local text = game.translate_string("st_cfm")
			SetHudMsg(text,3)
		end
	end
	
	-- Condition Checker mod
	if (ConditionCheckerModEnable and ConditionCheckerTools[obj:section()]) then
		local hud = get_hud()
		--hud:HideActorMenu()
		local ui = ui_con_checker and ui_con_checker.con_checker_ui(hud,obj:section())
		if (ui) then
			ui:ShowDialog(true)
			ui:FillList()
		end
	end

	-- Dummy Torch for Flashlight
	if (FlashlightModEnable and obj:section() == "device_torch_dummy") then
		local torch = db.actor:object("device_torch")
		if not (has_alife_info("enable_device_torch")) then
			give_info("enable_device_torch")
			if not (torch) then
				alife():create("device_torch",db.actor:position(),0,0,0)
			end
			SetHudMsg(game.translate_string("st_lamp_equipped"),4)
		end
	end
	
	-- Deployable mgun
	if (obj:section() == "itm_deployable_mgun") then
		local pos = vector():set(device().cam_pos)
		pos:add(device().cam_dir:mul(3))
		alife():create("deployable_mgun",pos,level.vertex_id(pos),db.actor:game_vertex_id())
	end
	
	
	-- Geiger
	if (obj:section() == "geiger_dead") then
		local text = game.translate_string("st_rad_level")..": "..math.floor(db.actor.radiation*10000*0.387).." "..game.translate_string("st_msv")
		SetHudMsg(text,3)
	end
	
	
	local se_obj = alife_object(obj:id())
	if se_obj then
	
		-- Med-packs
		if (se_obj:section_name() == "medkit_ai1") or (se_obj:section_name()=="medkit_ai2") or (se_obj:section_name()=="medkit_ai3") then
			local sec = se_obj:section_name() .. "_content"
			
			if (ini_med:section_exist(sec)) then
				local n = ini_med:line_count(sec) or 0
				for i=0, n-1 do
					local result, id, value = ini_med:r_line(sec , i , "", "")
					if (system_ini():section_exist(id)) then
						alife():create(id, db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
					end
				end
			end
		end 
		
		-- Everything else
		if string.find(se_obj:section_name(),"ration_ukr_")
		or string.find(se_obj:section_name(),"ration_ru_")
		or string.find(se_obj:section_name(),"mre_")
		or string.find(se_obj:section_name(),"drug_sleepingpills_")
		or string.find(se_obj:section_name(),"drug_coagulant_")
		or string.find(se_obj:section_name(),"drug_antidot_")
		or string.find(se_obj:section_name(),"drug_radioprotector_")
		or string.find(se_obj:section_name(),"antibio_sulfad")
		or string.find(se_obj:section_name(),"antiemetic") then
			local uses = system_ini():r_float_ex(obj:section(),"uses_index")
			local base = system_ini():r_string_ex(obj:section(),"uses_base")
			
			if uses and uses >=2 and base and system_ini():section_exist(base) then
				local sec = trx_utils.get_multi_item (base, uses, -1)
				if sec and system_ini():section_exist(sec) then
					alife():create(sec, db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
				end
			end
		end
		
		if (se_obj:section_name()=="chocolate") then
			alife():create("chocolate_p", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
		end
		
	end
	
end

function actor_on_item_take(obj)
	if (obj:section() == "explosive_mobiltank")
	or (obj:section() == "explosive_tank")
	then
		alife():release( alife():object(obj:id()) ,true)
		local fuel = math.random(6,8)
		alife():create("explo_jerrycan_fuel"..fuel,db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
	end
end

function actor_on_item_take_from_box(box,obj) -- bind_stalker take_item_from_iventory_box
	if not (box) then
		return
	end

	if not (obj) then
		return
	end

	-- Backpack section
	if (BackPackStashEnable and box:section() == "inv_backpack") then
		if (box:is_inv_box_empty()) then
			local hud = get_hud()
			if (hud) then
				hud:HideActorMenu()
			end

			level.map_remove_object_spot(box:id(), BackPackStashSpot)
			alife():create("itm_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())

			alife():release( alife():object(box:id()) ,true)
		end
	end

	-- Actor backpack section
	if (ActorBackPackEnable and box:section() == "inv_actor_backpack") then
		if (box:is_inv_box_empty()) then
			local hud = get_hud()
			if (hud) then
				hud:HideActorMenu()
			end

			level.map_remove_object_spot(box:id(), BackPackActorSpot)

			alife():release( alife():object(box:id()) ,true)

			alife():create("itm_actor_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())

			utils.save_var(db.actor,"actor_inv_backpack_id",nil)
			db.actor:disable_info_portion("actor_filled_backpack")
		end
	end
end

function physic_object_on_use_callback(obj,who) -- bind_physic_object use_callback
	if (SleepBagEnable and SleepBagPlaceableSections[obj:section()]) then
		local hud = get_hud()
		if (hud) then
			hud:HideActorMenu()
		end
		ui_sleep_dialog.sleep_bag(obj:id(),SleepBagPlaceableSections[obj:section()])
	end
end

function on_key_press(key)
	local obj = db.actor:active_detector()
	if (obj and FlashlightSections[obj:section()]) then
	local bind = dik_to_bind(key)
		if bind == key_bindings.kTORCH then
			FlashlightFar = not FlashlightFar
			xr_sound.set_sound_play(db.actor:id(),"torch_click")
		end
	end
end

function on_item_drag_dropped(obj_1, obj_2, slot_from, slot_to) -- gather items

	-- check capability
	if not (slot_from == EDDListType.iActorBag and slot_to == EDDListType.iActorBag) then
        return
    end
	
	local uses_1 = system_ini():r_float_ex(obj_1:section(),"uses_index")
	local base_1 = system_ini():r_string_ex(obj_1:section(),"uses_base")
	local uses_2 = system_ini():r_float_ex(obj_2:section(),"uses_index")
	local base_2 = system_ini():r_string_ex(obj_2:section(),"uses_base")
	
	if (not uses_1) or (not base_1) or (not uses_2) or (not base_2) or (not system_ini():section_exist(base_1)) or (not system_ini():section_exist(base_2)) then
		return
	end
	
	if (base_1 ~= base_2) then
		return
	end
	
	-- get new item section
	local sec = trx_utils.get_multi_item (base_1, uses_1, uses_2)
	if (not sec) or (not system_ini():section_exist(sec)) then
		return
	end
	
	-- gather item 1
	local item_1
	local item_tbl_1 = {}
	local function search_1(temp, item)
		if (item:section() == obj_1:section()) then
			item_tbl_1[#item_tbl_1+1] = item
		end
	end
	db.actor:iterate_inventory(search_1,nil)
	
	if (#item_tbl_1 == 0) then
		return
	end
	item_1 = item_tbl_1[math.random(#item_tbl_1)]
	
	
	-- gather item 2
	local item_2
	local item_tbl_2 = {}
	local function search_2(temp, item)
		if (item:section() == obj_2:section()) and (item:id() ~= item_1:id()) then
			item_tbl_2[#item_tbl_2+1] = item
		end
	end
	db.actor:iterate_inventory(search_2,nil)
	
	if (#item_tbl_2 == 0) then
		return
	end
	item_2 = item_tbl_2[math.random(#item_tbl_2)]
	
	printf("TRX - Combine Items | item_1: " .. item_1:section() .. " [" .. item_1:id() .. "] | item_2: " .. item_2:section() .. " [" .. item_2:id() .. "] | New: " .. sec)
	
	-- remove old items, create the new one
	local se_obj_1 = alife_object(item_1:id())
	local se_obj_2 = alife_object(item_2:id())
	alife():release(se_obj_1,true)
	alife():release(se_obj_2,true)
	alife():create(sec, db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	
end

function on_item_focus(itm)
	local section = itm:section()
	if (RepairTools[section]) then 
		local ini = system_ini()
		local repair_type = ini:r_string_ex(section,"repair_type")
		if not (repair_type) then 
			return
		end
		
		local function itr(obj)
			if (repair_type == "weapon" and IsWeapon(obj)) then 
				return true 
			elseif (repair_type == "outfit") and (IsOutfit(obj) or IsHeadgear(obj)) then 
				return true
			elseif (repair_type == "all") then 
				local cls = obj:clsid()
				if (IsWeapon(nil,cls) or IsOutfit(nil,cls) or IsHeadgear(nil,cls)) then 
					return true 
				end
			end
			return false
		end 
		
		ActorMenu.get_actor_menu():highlight_for_each_in_slot(itr)
	end 
end


--=======================================< Special item use names >=======================================--

function inv_item_reveal_menu(itm) -- return "Reveal" name

	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	return game.translate_string("st_item_reveal")
end

function inv_item_open_menu(itm) -- return "Open" name

	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	return game.translate_string("st_item_open")
end

function inv_item_sort_menu(itm) -- return "Sort" name

	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	return game.translate_string("st_item_sort")
end

function inv_item_separate_menu(itm) -- return "Separate" name

	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	return game.translate_string("st_item_separate")
end


--=======================================< Special item use functions >=======================================--

function inv_item_use(obj) -- use item
	local se_obj = alife():object(obj:id())
	local p = obj:parent()
	if not (p and p:id() == db.actor:id()) then
		return
	end
	
	-- Craft mod
	if 	(obj:section() == "itm_drugkit") or (obj:section() == "itm_ammokit") or (obj:section() == "itm_repairkit_tier_1") or (obj:section() == "itm_repairkit_tier_2") or (obj:section() == "itm_repairkit_tier_3") then
		local hud = get_hud()
		hud:HideActorMenu()
		local ui = ui_itm_craft and ui_itm_craft.craft_ui(hud,obj,obj:section())
		if (ui) then
			ui:ShowDialog(true)
		end	
	end
	
	-- Map mod
	if 	(system_ini():r_string_ex(obj:section(),"use_map")) then
		local hud = get_hud()
		hud:HideActorMenu()
		local ui = ui_itm_map and ui_itm_map.map_ui(hud,obj,obj:section())
		if (ui) then
			ui:ShowDialog(true)
		end	
	end
	
	-- Personal Journal
	if (obj:section() == "journal") then
		coc_treasure_manager.create_random_stash(nil,nil,nil)
		alife():release(se_obj,true)
	end
	
	-- Ammo Box
	if (obj:section() == "ammo_box") then
		local max_ammo = math.random(1,5)
		local ammo_list = {}
		
		local ini_ammo = ini_file("misc\\items\\item_management\\ammo_box.ltx")
		local n = ini_ammo:line_count("ammo_list") or 0
		for i=0, n-1 do
			local result, id, value = ini_ammo:r_line("ammo_list" , i , "", "")
			
			if (tostring(id) == "size") and value then
				local t = alun_utils.str_explode(value,",")
				max_ammo = math.random(tonumber(t[1]) , tonumber(t[2])) or max_ammo
			end
			
			if system_ini():section_exist(tostring(id)) then
				ammo_list[#ammo_list + 1] = tostring(id)
			end
		end
		
		for i = 1, max_ammo do
			local ammo = ammo_list[math.random(#ammo_list)]
			if (ammo) then		
				create_ammo(ammo,db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),0,1)
			end
		end
		
		if (math.random(100) < 50) then
			alife():create("ammo_bad", db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
		end
		
		alife():release(se_obj)
	end
end

function inv_item_separate(obj) -- separate item
	local uses = system_ini():r_float_ex(obj:section(),"uses_index")
	local base = system_ini():r_string_ex(obj:section(),"uses_base")
	
	if (not uses) or (not base) or (not system_ini():section_exist(base)) then
		return
	end
	
	if (uses < 2) then
		return
	end
	
	local sec = trx_utils.get_multi_item (base, uses, -1)
	if (not sec) or (not system_ini():section_exist(sec)) then
		return
	end
	
	printf("TRX - Separate items | old item: " .. obj:section() .. " | new item 1: " .. base .. " | new item 2: " .. sec)
	
	local se_obj = alife_object(obj:id())
	alife():release(se_obj,true)
	alife():create(base, db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	alife():create(sec, db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
end


--=======================================< Others >=======================================--

function campfire_cook()
	for i=1,65535 do
		local zx = alife():object(i)
		if zx then
			local zn = level.object_by_id(zx.id)
			if zn then
				local cfm = zn:get_campfire()
				if cfm and zn:position():distance_to(db.actor:position()) < 1.5 then
					if (cfm:is_on()) then 
						return true
					else
						return false
					end
					return false
				end
			end
		end
	end
end

function check_actor_backpack()
	if (db.actor:has_info("actor_filled_backpack"))then
		return
	end

	local id = utils.load_var(db.actor,"actor_inv_backpack_id",nil)

	if not (id) then
		return
	end

	local se_obj = alife():object(id)
	if not (se_obj) then 
		return 
	end
	local st = db.storage[se_obj.id]
	local obj = st and st.object or level.object_by_id(id)

	if not (obj) then
		return
	end

	if (db.actor:has_info("actor_made_wish_for_riches")) then
		return 
	end
	
	local function itr_inv(temp,item)
		local id = item and item:section() ~= "itm_actor_backpack" and ActorBackPackKeep[item:section()] == nil and item:id()
		if (id and not is_ammo_for_wpn(item:section())) then
			local itm_slot
			local equipped
			for i=1,12 do
				if (i ~= 4) then
					itm_slot = db.actor:item_in_slot(i)
					if (itm_slot and itm_slot:id() == id) then
						equipped = true
						break
					end
				end
			end
			
			if (db.actor:is_on_belt(item)) then
				equipped = true
			end

			if (not equipped) then
				db.actor:transfer_item(item,obj)
			end
			equipped = nil
		end
	end

	db.actor:iterate_inventory(itr_inv)

	db.actor:give_info_portion("actor_filled_backpack")
end

function actor_on_trade(obj,sell_bye,money) -- bind_stalker on_trade

end

function actor_item_take(obj) -- bind_stalker on_item_take

end

function npc_on_item_take_from_box(npc,box,item)

end

function is_ammo_for_wpn(sec)
	local sim = alife()
	for i=2,3 do
		local wpn = db.actor:item_in_slot(i)
		if (wpn) then
			local ammos = alun_utils.parse_list(system_ini(),wpn:section(),"ammo_class",true)
			if (ammos[sec]) then 
				return true 
			end
		end
	end
	return false
end

function loot_mutant(obj,clsid,t,npc,dont_create)
	-- if not (db.actor) then 
	-- 	return 
	-- end 
	
	local clsid = clsid or obj and obj:clsid()
	if not (clsid) then
		return
	end

	local loot_table = alun_utils.collect_section(ini,clsid_to_section[clsid])

	local loot,sec
	for i=1,#loot_table do
		loot = alun_utils.str_explode(loot_table[i],",")
		if (loot and loot[1] and loot[2]) then
			if not (loot[3]) then
				loot[3] = 1
			end

			loot[2] = tonumber(loot[2])
			for i=1,loot[2] do
				if (math.random() <= tonumber(loot[3])) then
					--alun_utils.printf("loot_mutant: section=%s",loot[1])
					local se_obj
					if not dont_create then
						se_obj = alife():create(loot[1],npc and npc:position() or db.actor:position(),0,0,npc and npc:id() or 0)
					end
					if (t) then
						local item_section = loot[1]
						if not (t[item_section]) then
							t[item_section] = {}
						end
						t[item_section].count = t[item_section].count and t[item_section].count + 1 or 1
						if se_obj then t[item_section][t[item_section].count] = se_obj.id end
						--alun_utils.printf("loot_mutant")

						if npc and npc:id() ~= db.actor:id() then
							alife():create(loot[1],npc:position(),0,0,npc:id())
						end
					end
				end
			end
		end
	end
	
	-- Unlock relevant mutant article in guide.
	if (not npc) then
		dxr_encyclopedia.detect_mutant_interaction(clsid_to_section[clsid])
	end
end
--end of insertion