---------------------------------------
--	itms_manager
--
-- by Alundaio
---------------------------------
--[[
Copyright (C) 2012 Alundaio
This work is licensed under a Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License-]]
--]]

-- =======================================================================================
-- Modified by Tronex
-- 2018/7/18 - Added support for new usable items (maps,craft)
-- 2018/7/21 - Added the ability to gather/separate muti-use items
-- 2018/7/26 - Added the ability to disassemble misc items
-- 2018/7/26 - Rewrote a lot of function with better codes
-- 2018/7/31 - Added new items, battery consumption for geiger counter and gps tracker
-- 2018/8/2  - Drag artefacts on containers to put them, container tool is not used
-- =======================================================================================

-- Prepare ini files
local ini = system_ini()
local ini_manager = ini_file("plugins\\item_management\\itms_manager.ltx")
local ini_med = ini_file("plugins\\item_management\\med_packs.ltx")
local ini_mutant = ini_file("plugins\\item_management\\mutant_loot.ltx")
local ini_battery = ini_file("plugins\\item_management\\axr_battery.ltx")
local ini_container = ini_file("plugins\\item_management\\arty_container.ltx")

-- Collect item sections of main tools
craft_tools = {}
recipe_tools = {}
repair_tools = {}
disassemble_tools = {}
cook_tools = {}
map_tools = {}
letter_tools = {}
battery_tools = alun_utils.collect_section(ini_battery,"battery_sections",true)
artefact_containers = alun_utils.collect_section(ini_container,"containers",true) or {}
ini:section_for_each(function(section) -- search all sections
	if ini:r_bool_ex(section,"craft_tool") then
		craft_tools[section] = true
	elseif ini:r_bool_ex(section,"recipe") then
		recipe_tools[section] = true
	elseif ini:r_bool_ex(section,"repair_tool") then
		repair_tools[section] = true
	elseif ini:r_bool_ex(section,"disassemble_tool") then
		disassemble_tools[section] = true
	elseif ini:r_bool_ex(section,"cooking_tool") then
		cook_tools[section] = true
	elseif ini:r_string_ex(section,"use_map") then
		map_tools[section] = true
	elseif ini:r_bool_ex(section,"letter") then
		letter_tools[section] = true
	end
end)

--Backpack stash mod
local BackPackStashEnable = ini_manager:r_bool_ex("backpack_stash","enable",false)
local BackPackStashAllowInBase = BackPackStashEnable and ini_manager:r_bool_ex("backpack_stash","allow_in_base",false)
local BackPackStashSpot = BackPackStashEnable and ini_manager:r_string_ex("backpack_stash","map_spot") or "treasure" 
local BackPackStashEnableTip = BackPackStashEnable and ini_manager:r_bool_ex("backpack_stash","enable_news_tip",false)
local BackPackStashEnableUi = BackPackStashEnable and ini_manager:r_bool_ex("backpack_stash","enable_ui",false)

-- Sleep bag mod
local SleepBagEnable = ini_manager:r_bool_ex("sleeping_bag","enable",true)
local SleepBagRadius = SleepBagEnable and ini_manager:r_float_ex("sleeping_bag","unsafe_radius") or 5000
local SleepBagPlaceable = SleepBagEnable and ini_manager:r_bool_ex("sleeping_bag","use_placeable",false)
local SleepBagGameStart = SleepBagEnable and ini_manager:r_bool_ex("sleeping_bag","have_at_start",false)
local SleepBagSections = SleepBagEnable and alun_utils.collect_section(ini_manager,"sleeping_bag_sections",true)
local SleepBagPlaceableSections = SleepBagEnable and alun_utils.collect_section(ini_manager,"sleeping_bag_ph_sections",true)

-- Actor backpack mod
local ActorBackPackEnable = ini_manager:r_bool_ex("actor_backpack","enable",false)
local ActorBackPackSpot = ActorBackPackEnable and ini_manager:r_string_ex("actor_backpack","map_spot") or "treasure"
local ActorBackPackSlot = ActorBackPackEnable and ini_manager:r_string_ex("actor_backpack","quick_slot") or "slot_3"
local ActorBackPackKeep = ActorBackPackEnable and alun_utils.collect_section(ini_manager,"actor_backpack_keep_items",true)
local ActorBackPackForced = ActorBackPackEnable and ini_manager:r_bool_ex("actor_backpack","actor_backpack_always_have",false)

-- Loot Mutant
local MutantLootDecayTime = ini_mutant:r_float_ex("mutant_loot_mod","decay_time") or 7200

-- Flashlight mod
local FlashlightModEnable = ini_manager:r_bool_ex("flashlight_mod","enable",false)
local FlashlightSections = FlashlightModEnable and alun_utils.collect_section(ini_manager,"flashlight_sections",true)
local FlashlightFar = false

-- Static Message
ShowMessage = nil
ShowMessageInit = nil
ShowMessageTime = nil

TorchType = 0
local torch_delay
local d_flag = false
local actor_fill_backpack
local clsid_to_section = {
	--> TRX A-Life Revamp
	[clsid.psysucker_s]		= "psysucker",
	[clsid.lurker_s]		= "lurker",
	[clsid.karlik_s]		= "karlik",
	
	[clsid.bloodsucker_s] 	= "bloodsucker",
	[clsid.boar_s] 			= "boar",
	[clsid.burer_s] 		= "burer",
	[clsid.chimera_s]		= "chimera",
	[clsid.controller_s]	= "controller",
	[clsid.dog_s]			= "dog",
	[clsid.flesh_s]			= "flesh",
	[clsid.gigant_s]		= "gigant",
	[clsid.poltergeist_s]	= "poltergeist",
	[clsid.psy_dog_s]		= "psy_dog",
	[clsid.psy_dog_phantom_s] = "psy_dog",
	[clsid.pseudodog_s]		= "pseudodog",
	[clsid.snork_s]			= "snork",
	[clsid.tushkano_s]		= "tushkano",
	[clsid.cat_s]			= "cat",
	[clsid.fracture_s]		= "fracture",
	[clsid.zombie_s]		= "zombie",
	[clsid.crow]			= "crow",
	[clsid.rat_s]			= "rat"
}


--=======================================< Callbacks >=======================================--

function on_game_start()
	RegisterScriptCallback("on_game_load",on_game_load)
	RegisterScriptCallback("actor_on_update",actor_on_update)
	RegisterScriptCallback("actor_on_item_drop",actor_on_item_drop)
	RegisterScriptCallback("monster_on_actor_use_callback",monster_on_actor_use_callback)
	RegisterScriptCallback("actor_on_item_use",actor_on_item_use)
	RegisterScriptCallback("actor_on_item_take",actor_on_item_take)
	RegisterScriptCallback("actor_on_item_take_from_box",actor_on_item_take_from_box)
	RegisterScriptCallback("physic_object_on_use_callback",physic_object_on_use_callback)
	RegisterScriptCallback("on_key_press",on_key_press)
	RegisterScriptCallback("on_key_release",on_key_release)
	RegisterScriptCallback("CUIActorMenu_OnItemDropped",on_item_drag_dropped)
	--RegisterScriptCallback("CUIActorMenu_OnItemFocusReceive",on_item_focus)
end

function on_game_load()


	if (ActorBackPackEnable and ActorBackPackForced) then
		local actor_itm_backpack_id= utils.load_var(db.actor,"actor_itm_backpack_id",nil)
		local actor_inv_backpack_id = utils.load_var(db.actor,"actor_inv_backpack_id",nil)
		if (not actor_itm_backpack_id and not actor_inv_backpack_id) then
			get_console():execute(ActorBackPackSlot.." itm_actor_backpack")
			local se_obj = alife():create("itm_actor_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),0)
			if (se_obj) then
				utils.save_var(db.actor,"actor_itm_backpack_id",se_obj.id)
			end
		end
	end

	--[[
	if (SleepBagEnable and SleepBagGameStart) then
		local sleepbag_id = utils.load_var(db.actor,"itm_sleepbag_id",nil)
		if (not sleepbag_id) then
			local se_obj = alife():create("itm_sleepbag",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),0)
			utils.save_var(db.actor,"itm_sleepbag_id",se_obj.id)
		end
	end
	--]]
	
	-- Set up maximum weight
	local cw = hardcore_economy.get_factor("weight") or 60
	local mww = cw + (math.ceil(cw / 5) * 2)
	if (cw ~= db.actor:get_actor_max_weight()) then
		db.actor:set_actor_max_weight(cw)
		db.actor:set_actor_max_walk_weight(mww)
	end
end

function actor_on_update()

	if not has_alife_info("start_equipement_damaged") then
		xr_effects.damage_actor_items()
		give_info("start_equipement_damaged")
	end

	check_actor_backpack()

	if (FlashlightModEnable) then
		local obj = db.actor:active_detector()
		local torch = db.actor:object("device_torch")
		if (obj and FlashlightSections[obj:section()]) then
			if (has_alife_info("enable_device_torch")) then
				db.actor:disable_info_portion("enable_device_torch")
				alife():create("device_torch_dummy",db.actor:position(),0,0,0)
				SetHudMsg(game.translate_string("st_lamp_disconnected"),5)
			end

			if not (torch) then
				alife():create("device_torch",db.actor:position(),0,0,0)
			end

			if (FlashlightFar) then
				TorchType = 1
			else
				TorchType = 2
			end
			
			if (torch and not torch:torch_enabled()) then
				if not (torch_delay) then
					torch_delay = time_global() + 1000
				end

				if (time_global() > torch_delay) then
					torch:enable_torch(true)
				end
			end
		else
			if (torch and not has_alife_info("enable_device_torch")) then
				TorchType = 0
				FlashlightFar = false;
				if (torch:torch_enabled()) then
					torch:enable_torch(false)
					torch_delay = nil
				end
			end
		end
	end
end

function actor_on_item_drop(obj) -- bind_stalker on_item_drop
	if not (obj) then
		return
	end
	if (ActorBackPackEnable and ActorBackPackForced and obj:section() == "itm_actor_backpack") then
		local se_itm = alife():create("itm_actor_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())

		if not (se_itm) then
			return
		end

		utils.save_var(db.actor,"actor_itm_backpack_id",se_itm.id)
		alife():release( alife():object(obj:id()) )
	end
	
	if (db.actor:has_info("actor_made_wish_for_riches")) then 
		db.actor:transfer_item(obj,db.actor)
	end
end

function monster_on_actor_use_callback(obj,who) -- Open mutant loot UI

	local looted = utils.se_obj_load_var(obj:id(),obj:name(),"looted")
	if (looted) then
		return
	end

	if (obj:clsid() == clsid.crow) then
		utils.save_var(obj, "looted", true)
	else
		utils.se_obj_save_var(obj:id(),obj:name(),"looted",true)
	end

	xr_corpse_detection.set_valuable_loot(obj:id(),false)

	local st = db.storage[obj:id()]
	if (st and st.death_time and game.get_game_time():diffSec(st.death_time) > MutantLootDecayTime) then
		SetHudMsg(game.translate_string("st_body_decayed"),4)
	else
		local hud = get_hud()
		if (hud) then
			ui_mutant_loot.loot_ui(hud,obj,obj:id(),obj:section(),obj:clsid())
		end
	end
end

function actor_on_item_use(obj) -- bind_stalker on_item_use
	if (db.actor:has_info("actor_made_wish_for_riches")) then
		return 
	end
	
	local name = obj:section()

	-- Backpack
	if (BackPackStashEnable and name == "itm_backpack") then

		if (BackPackStashAllowInBase ~= true) then
			local in_base
			local zone
			local t = {"zat_a2_sr_no_assault","jup_a6_sr_no_assault","jup_b41_sr_no_assault"}
			for i=1,#t do
				zone = db.zone_by_name[t[i]]
				if (zone and zone:inside(db.actor:position())) then
					in_base = true
					break
				end
			end

			if (in_base) then
				SetHudMsg(game.translate_string("st_stash_unsafe"),4)
				alife():create("itm_backpack",db.actor:position(),0,0,0)
				return
			end
		end

		local se_obj = alife():create("inv_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
		if (se_obj) then
			local level_name = level.name()

			if not (BackPackStashEnableUi) then
				local count = utils.load_var(db.actor, level_name.."bpk_count", 0)
				utils.save_var(db.actor, level_name.."bpk_count", count+1)
				level.map_add_object_spot_ser(se_obj.id, BackPackStashSpot, level_name.." stash "..count+1)
			else
				local hud = get_hud()
				if (hud) then
					hud:HideActorMenu()
					local ui = ui_itm_backpack and ui_itm_backpack.backpack_ui(hud,se_obj.id,BackPackStashSpot)
					if (ui) then
						ui:ShowDialog(true)
					end
				end
			end

			if (BackPackStashEnableTip) then
				SetHudMsg(game.translate_string("st_stash_created"),4)
			end
		end
		return
	end

	-- Sleeping bag
	if (SleepBagEnable and SleepBagSections[name]) then
		local sec = name
		if (SleepBagPlaceable) then
			local ph_sec = ini:r_string_ex(sec,"placeable_section")
			local se_obj = alife():create(ph_sec or "ph_sleepbag",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())
			local compr = alife():create("compression_bag",db.actor:position(),0,0,0)
		else
			local se_obj = alife():create(sec,db.actor:position(),0,0,0)
			local hud = get_hud()
			if (hud) then
				hud:HideActorMenu()
			end
			local ui = ui_sleep_dialog.sleep_bag(se_obj,sec)
		end
		return
	end
	
	if (name == "compression_bag") then use_compression_bag(obj) end

	-- Actor backpack
	if (ActorBackPackEnable and name == "itm_actor_backpack") then
		local id = ActorBackPackForced and utils.load_var(db.actor,"actor_inv_backpack_id",nil)
		if (id) then
			SetHudMsg(game.translate_string("st_stash_placed"),4)
			alife():create("itm_actor_backpack",db.actor:position(),0,0,0)
			return
		end

		local se_obj = alife():create("inv_actor_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id())

		level.map_add_object_spot_ser(se_obj.id, ActorBackPackSpot,"Ðþêçàê ñòàëêåðà "..db.actor:character_name())

		utils.save_var(db.actor,"actor_inv_backpack_id",se_obj.id)
	end

	-- Dummy Torch for Flashlight
	if (FlashlightModEnable and name == "device_torch_dummy") then
		local torch = db.actor:object("device_torch")
		if not (has_alife_info("enable_device_torch")) then
			give_info("enable_device_torch")
			if not (torch) then
				alife():create("device_torch",db.actor:position(),0,0,0)
			end
			SetHudMsg(game.translate_string("st_lamp_equipped"),4)
		end
	end
	
	-- Condition Checker
	-- if (name == "con_checker") then use_con_checker(obj) end
	
	-- Repair tools
	--if repair_tools[name] then use_tool(obj) end

	-- Deployable mgun
	if (name == "itm_deployable_mgun") then use_deployable_mgun(obj) end
	
	-- Geiger
	if (name == "geiger_dead") then use_gieger(obj) end
	
	-- GPS Tracker
	if (name == "gps_tracker") then use_tracker(obj,nil) end
	
	-- Watch
	if (name == "hand_watch") then use_watch(obj) end
	
	local se_obj = alife_object(obj:id())
	if se_obj then
		
		-- Everything else
		local uses = ini:r_float_ex(name,"uses_index")
		local base = ini:r_string_ex(name,"uses_base")
		if uses and uses >=2 and base and ini:section_exist(base) then
			if string.find(se_obj:section_name(),"ration_ukr_")
			or string.find(se_obj:section_name(),"ration_ru_")
			or string.find(se_obj:section_name(),"mre_")
			or string.find(se_obj:section_name(),"drug_sleepingpills_")
			or string.find(se_obj:section_name(),"drug_coagulant_")
			or string.find(se_obj:section_name(),"drug_antidot_")
			or string.find(se_obj:section_name(),"drug_radioprotector_")
			or string.find(se_obj:section_name(),"antibio_sulfad")
			or string.find(se_obj:section_name(),"antiemetic") then
				local sec = trx_utils.get_item_charge (base, uses, -1)
				trx_utils.create_inv_obj(sec)
			end
		end
		
		if (se_obj:section_name()=="chocolate") then trx_utils.create_inv_obj("chocolate_p") end
	end
	
end

function actor_on_item_take(obj) -- explosive item special
	if (obj:section() == "explosive_mobiltank") or (obj:section() == "explosive_tank") then
		alife():release( alife():object(obj:id()) ,true)
		local fuel = math.random(6,8)
		alife():create("explo_jerrycan_fuel" .. fuel,db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())
	end
	
	-- Set medkits uses to 1 on hardcore economy
	if (string.find(obj:section(),"medkit")) then
		local uses = obj:get_remaining_uses()
		local num = hardcore_economy.get_factor("multiuse_medkits")
		if (uses > num) then
			obj:set_remaining_uses(num)
		end
	end
	
	--db.actor:give_game_news(" ", "%c[0,170,170,100]" .. alun_utils.get_inv_name(obj:section()), "ui_inGame2_D_Ohotnik_na_mutantov", 0, 1500, 0)
end

function actor_on_item_take_from_box(box,obj) -- bind_stalker take_item_from_iventory_box
	if not (box) then
		return
	end

	if not (obj) then
		return
	end

	-- Backpack section
	if (BackPackStashEnable and box:section() == "inv_backpack") then
		if (box:is_inv_box_empty()) then
			local hud = get_hud()
			if (hud) then
				hud:HideActorMenu()
			end

			level.map_remove_object_spot(box:id(), BackPackStashSpot)
			alife():create("itm_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())

			alife():release( alife():object(box:id()) ,true)
		end
	end

	-- Actor backpack section
	if (ActorBackPackEnable and box:section() == "inv_actor_backpack") then
		if (box:is_inv_box_empty()) then
			local hud = get_hud()
			if (hud) then
				hud:HideActorMenu()
			end

			level.map_remove_object_spot(box:id(), BackPackActorSpot)

			alife():release( alife():object(box:id()) ,true)

			alife():create("itm_actor_backpack",db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),db.actor:id())

			utils.save_var(db.actor,"actor_inv_backpack_id",nil)
			db.actor:disable_info_portion("actor_filled_backpack")
		end
	end
end

function physic_object_on_use_callback(obj,who) -- bind_physic_object use_callback
	if (SleepBagEnable and SleepBagPlaceableSections[obj:section()]) then
		local hud = get_hud()
		if (hud) then
			hud:HideActorMenu()
		end
		ui_sleep_dialog.sleep_bag(obj:id(),SleepBagPlaceableSections[obj:section()])
	end
end

function on_key_press(key) -- turn off flashlight if actor don't have it
	local obj = db.actor:active_detector()
	if (obj and FlashlightSections[obj:section()]) then
		local bind = dik_to_bind(key)
		if bind == key_bindings.kTORCH then
			FlashlightFar = not FlashlightFar
			xr_sound.set_sound_play(db.actor:id(),"torch_click")
		end
	end
	
	if(key == DIK_keys["DIK_LCONTROL"] ) then
		d_flag = true
	end
end

function on_key_release(key)
	if(key == DIK_keys["DIK_LCONTROL"] ) then
		d_flag = false
	end
end

function on_item_drag_dropped(obj_1, obj_2, slot_from, slot_to)

	-- Check capability
	if not (slot_from == EDDListType.iActorBag and slot_to == EDDListType.iActorBag) then
        return
    end
	
	-- Put artefact in container
	if artefact_containers[obj_2:section()] then
		if (ini:r_string_ex(obj_1:section(),"class") == "ARTEFACT") or (ini:r_string_ex(obj_1:section(),"class") == "SCRPTART") then
			--local delay = 30
			local cont = obj_2:section()
			local arty = obj_1:section()
			--local arty_o = level.object_by_id(obj_1:id())
			--local arty_cond = arty_o:condition()
			
			if ini:section_exist(arty .. "_" .. cont) then
				trx_utils.create_inv_obj(arty .. "_" .. cont)
				trx_utils.release_obj(obj_1)
				trx_utils.release_obj(obj_2)
				
				if actor_effects.use_item("container_tool_" .. cont .. "_dummy") then
					actor_effects.use_item("container_tool_" .. cont .. "_dummy")
					--level_weathers.get_weather_manager():forced_weather_change()
				end
				
				--[[ Carrying artefact condition over the container
				-- Funnily enough, the new added item in inventory don't register quickly? so a timer is necessary
				local function timer()
					local cont_arty = trx_utils.collect_inv_obj(arty .. "_" .. cont , 0) or {}
					for i=1,#cont_arty do
						local cont_arty_o = level.object_by_id(cont_arty[i]:id())
						if (cont_arty_o:condition() > 0.99) then
							cont_arty_o:set_condition(arty_cond)
							break
						end
					end
					return true
				end
				CreateTimeEvent("container","delay",delay,timer)
				--]]
			end
		end
		
	-- Combine multi-use items
	else 
		local uses_1 = ini:r_float_ex(obj_1:section(),"uses_index")
		local base_1 = ini:r_string_ex(obj_1:section(),"uses_base")
		local uses_2 = ini:r_float_ex(obj_2:section(),"uses_index")
		local base_2 = ini:r_string_ex(obj_2:section(),"uses_base")
		
		if (not uses_1) or (not base_1) or (not uses_2) or (not base_2) or (not ini:section_exist(base_1)) or (not ini:section_exist(base_2)) then
			return
		end
		
		if (base_1 ~= base_2) then
			return
		end
		
		-- Get new item section
		local sec = trx_utils.get_item_charge (base_1, uses_1, uses_2)
		if (not sec) or (not ini:section_exist(sec)) then
			return
		end
		
		-- Collect old items (objects)
		local item_1_tbl = trx_utils.collect_inv_obj (obj_1:section(),1)
		local item_1 = item_1_tbl and item_1_tbl[1] or nil
		if (not item_1) then return end
		
		local item_2_tbl = trx_utils.collect_inv_obj (obj_2:section(),1,item_1:id())
		local item_2 = item_2_tbl and item_2_tbl[1] or nil
		if (not item_2) then return end
		
		printf("TRX - Combine Items | item_1: " .. item_1:section() .. " [" .. item_1:id() .. "] | item_2: " .. item_2:section() .. " [" .. item_2:id() .. "] | New: " .. sec)
		
		-- Remove old items, create the new one
		local se_obj_1 = alife_object(item_1:id())
		local se_obj_2 = alife_object(item_2:id())
		alife():release(se_obj_1,true)
		alife():release(se_obj_2,true)
		alife():create(sec, db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
	end
end

function on_item_focus(itm) -- highlight compatible repair items
	local section = itm:section()
	if (repair_tools[section]) then 
		local repair_type = ini:r_string_ex(section,"repair_type")
		if not (repair_type) then 
			return
		end
		
		local function itr(obj)
			if (repair_type == "weapon" and IsWeapon(obj)) then 
				return true 
			elseif (repair_type == "outfit") and (IsOutfit(obj) or IsHeadgear(obj)) then 
				return true
			elseif (repair_type == "all") then 
				local cls = obj:clsid()
				if (IsWeapon(nil,cls) or IsOutfit(nil,cls) or IsHeadgear(nil,cls)) then 
					return true 
				end
			end
			return false
		end 
		
		ActorMenu.get_actor_menu():highlight_for_each_in_slot(itr)
	end 
end


--=======================================< Special item use names >=======================================--

function menu_use(itm) -- return "Use" name
	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	return game.translate_string("st_item_use")
end

function menu_reveal(itm) -- return "Reveal" name
	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	return game.translate_string("st_item_reveal")
end

function menu_charge(itm) -- return "Reveal" name
	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	if (not battery_tools[itm:section()]) then return end
	
	return game.translate_string("st_item_charge")
end

function menu_read(itm) -- return "Read" name
	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	return game.translate_string("st_item_read")
end

function menu_open(itm) -- return "Open" name
	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	if artefact_containers[itm:section()] then return end -- default containers
	
	return game.translate_string("st_item_open")
end

function menu_sort(itm) -- return "Sort" name
	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	return game.translate_string("st_item_sort")
end

function menu_play(itm) -- return "Play" name
	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	return game.translate_string("st_item_play")
end

function menu_separate(itm) -- return "Separate" name
	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	local uses = ini:r_float_ex(itm:section(),"uses_index")
	if (not uses) then return end
	if (uses < 2) then return end
	
	return game.translate_string("st_item_separate")
end

function menu_disassemble(itm) -- return "Reveal" name
	local p = itm:parent()
	if not (p and p:id() == db.actor:id()) then return end
	
	if (not ini:r_string_ex(itm:section(),"disassemble_parts")) then return end
	
	if (string.find(itm:section(), "(lead.-_box)",3)) then
		return	
	elseif (string.find(itm:section(), "(af.-_iam)",3)) then
		return
	elseif (string.find(itm:section(), "(af.-_aac)",3)) then
		return
	elseif (string.find(itm:section(), "(af.-_aam)",3)) then
		return
	end
	
	return game.translate_string("st_awr_disassembly_cloth")
end


--=======================================< Special item use functions >=======================================--

function use_tool(obj) -- use item
	local se_obj = alife():object(obj:id())
	local p = obj:parent()
	if not (p and p:id() == db.actor:id()) then
		return
	end
	
	local section = obj:section()
	
	local hud = get_hud()
	if (hud) then
		hud:HideActorMenu()
	end
	
	-- Crafting tools
	if craft_tools[section] then
		local ui = ui_itm_craft and ui_itm_craft.craft_ui(hud,obj,section)
		if (ui) then
			ui:ShowDialog(true)
		end	
	end
	
	-- Repair tools
	if repair_tools[section] then
		local ui = ui_itm_repair and ui_itm_repair.repair_ui(hud,obj,section)
		if (ui) then
			ui:ShowDialog(true)
		end	
	end
	
	-- Cooking tools
	if cook_tools[section] then
		local ui = ui_itm_cooking and ui_itm_cooking.cook_ui(hud,obj,section)
		if (ui) then
			ui:ShowDialog(true)
		end	
	end
	
	-- Map kits
	if 	map_tools[section] then
		local ui = ui_itm_map and ui_itm_map.map_ui(hud,obj,section)
		if (ui) then
			ui:ShowDialog(true)
		end	
	end
	
	-- Personal Journal
	if (section == "journal") then
		coc_treasure_manager.create_random_stash(nil,nil,nil)
		alife():release(se_obj,true)
	end
end

function use_separate(obj) -- separate item
	local base = ini:r_string_ex(obj:section(),"uses_base")
	
	if trx_utils.adjust_item_charge(obj,-1) then
		alife():create(base, db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
		--printf("TRX - inv_item_separate | Get new base item : " .. base)
	end
end

function use_disassemble(obj) -- disassemble item
	local chk = axr_main.config:r_value("mm_options","enable_awr_disassembly",1,true)
	if chk and (not d_flag) then
		awr_shared_functions.SendAwrMsg("success", "detail", "st_awr_ctrl")
		return
	end
	
	local delay = axr_main.config:r_value("mm_options","enable_extra_animations",1) and 42 or 0
	local name = alun_utils.get_inv_name(obj:section())

	-- Collect disassemble parts of our item
	local parts = ini:r_string_ex(obj:section(),"disassemble_parts")
	if (not parts) then return end
	local parts_tbl = alun_utils.str_explode(parts,",")
	local parts_text = ""
	for i=1,#parts_tbl do
		parts_text = parts_text .. "\\n¥ " .. alun_utils.get_inv_name(parts_tbl[i])
	end
	
	-- Collect disassemble tools (objects)
	local dis_itm
	for k,v in pairs (disassemble_tools) do
		local dis_tbl = trx_utils.collect_inv_obj(k,1)
		dis_itm = dis_tbl and dis_tbl[1] or nil
		if dis_itm then
			break
		end
	end
	if (not dis_itm) then 
		news_manager.send_tip(db.actor, game.translate_string("st_news_dis_items"), nil, "disassemble", 6000)
		return 
	end

	-- Delete old disassemble item or one use
	if (not trx_utils.adjust_item_charge(dis_itm,-1)) then
		trx_utils.release_obj(dis_itm)
		--printf("TRX - inv_item_disassemble | Delete disassembling tool: " .. dis_itm:section())
	end
		
	-- Delete old item or one use
	if (not trx_utils.adjust_item_charge(obj,-1)) then
		trx_utils.release_obj(obj)
		--printf("TRX - inv_item_disassemble | Delete disassembled item: " .. obj:section())
	end
	
	local function disasm()
	
		-- Send news
		awr_shared_functions.SendAwrMsg("success", "weapon_ammo", "st_dis_text_11", name, game.translate_string("st_dis_text_9"), parts_text)
	
		-- Give disassemble parts
		for i=1,#parts_tbl do
			if ini:section_exist(parts_tbl[i]) then
				alife():create(parts_tbl[i], db.actor:position(), db.actor:level_vertex_id(), db.actor:game_vertex_id(), db.actor:id())
				--printf("TRX - inv_item_disassemble | Get new part from disassembling: " .. parts_tbl[i])
			end
		end
		
		return true
	end
	
	actor_effects.use_item("disassemble_weapon_dummy")
	CreateTimeEvent("disasm","delay",delay,disasm,obj)
end

function use_ammo_box(obj)
	local max_ammo = math.random(1,5)
	local ammo_list = {}
	
	local ini_ammo = ini_file("plugins\\item_management\\ammo_box.ltx")
	local n = ini_ammo:line_count("ammo_list") or 0
	for i=0, n-1 do
		local result, id, value = ini_ammo:r_line("ammo_list" , i , "", "")
		
		if (tostring(id) == "size") and value then
			local t = alun_utils.str_explode(value,",")
			max_ammo = math.random(tonumber(t[1]) , tonumber(t[2])) or max_ammo
		end
		
		if ini:section_exist(tostring(id)) then
			ammo_list[#ammo_list + 1] = tostring(id)
		end
	end
	
	for i = 1, max_ammo do
		local ammo = ammo_list[math.random(#ammo_list)]
		if (ammo) then		
			create_ammo(ammo,db.actor:position(),db.actor:level_vertex_id(),db.actor:game_vertex_id(),0,1)
		end
	end
	
	if (math.random(100) < 50) then
		trx_utils.create_inv_obj("ammo_bad")
	end
	
	trx_utils.release_obj(obj)
end

function use_medpack(obj)
	local sec = obj:section() .. "_content"
		
	if (ini_med:section_exist(sec)) then
		actor_effects.use_item(obj:section())
		
		local n = ini_med:line_count(sec) or 0
		for i=0, n-1 do
			local result, id, value = ini_med:r_line(sec , i , "", "")
			trx_utils.create_inv_obj(id)
		end
		
		trx_utils.release_obj(obj)
	end
end

function use_gieger(obj)
	local threshold = alun_utils.read_from_ini(ini_battery,"main","gei_drain_speed","float",0.0001)
	
	-- Check out UPD power, return if power is low
	local power = axr_battery.getBatteryCondition()
	if power < threshold + 0.05 then
		SetHudMsg(game.translate_string("st_upd_low"),3)
		return
	end
	
	-- Show rad level
	local text = game.translate_string("st_rad_level") .. ": " .. math.floor(db.actor.radiation*10000*0.387) .. " " .. game.translate_string("st_msv")
	SetHudMsg(text,3)
	
	-- Consume power
	local battery = db.actor:object("wpn_upd")
	axr_battery.updateBatteryCondition(battery,power,"gei")
	
	-- Play sound
	--trx_utils.play_sound("interface\\inv_geiger")
end

function use_tracker(obj,target)
	target = target or nil
	local all = ini:r_bool_ex(obj:section(),"scan_all") or false
	local period = ini:r_float_ex(obj:section(),"scan_time") or 20
	local threshold = alun_utils.read_from_ini(ini_battery,"main","gps_drain_speed","float",0.0001)
	
	-- Hide inventory hud
	local hud = get_hud()
	if (hud) then
		hud:HideActorMenu()
	end
	
	-- Check out UPD power, return if power is low
	local power = axr_battery.getBatteryCondition()
	if power < threshold + 0.05 then
		SetHudMsg(game.translate_string("st_upd_low"),3)
		return
	end
	
	-- Show map
	local pda_menu = ActorMenu.get_pda_menu()
	if not (pda_menu:IsShown()) then 
		pda_menu:ShowDialog(true)
		pda_menu:SetActiveSubdialog("eptTasks")
	end

	-- Show npc markers
	squad_smart.active_tracker(period,all,target)
	
	-- Consume power
	local battery = db.actor:object("wpn_upd")
	axr_battery.updateBatteryCondition(battery,power,"gps")
	
	-- Play sound
	trx_utils.play_sound("interface\\inv_gps")
end

function use_compression_bag(obj)
	-- Compression bag
	for i=1,65535 do
		local s = alife():object(i)
		if s then
			local o = level.object_by_id(s.id)
			if o  then
				local slbag = o:section()
				if slbag == "ph_sleepbag" and o:position():distance_to(db.actor:position()) < 1 then
					alife():create("itm_sleepbag",db.actor:position(),0,0,0)
					alife():release(s)
					alife():release(alife():object(obj:id()))
					actor_effects.use_item("itm_sleepbag")
					break
				end
			end
		end
	end
end

function use_deployable_mgun(obj)
	local pos = vector():set(device().cam_pos)
	pos:add(device().cam_dir:mul(3))
	alife():create("deployable_mgun",pos,level.vertex_id(pos),db.actor:game_vertex_id())
end

function use_con_checker(obj)
	local hud = get_hud()
	--hud:HideActorMenu()
	local ui = ui_con_checker and ui_con_checker.con_checker_ui(hud,obj:section())
	if (ui) then
		ui:ShowDialog(true)
		ui:FillList()
	end
end

function use_recipe(obj)
	local sec = obj:section()
	if not recipe_tools[sec] then
		return
	end
	
	local guide = ui_pda_encyclopedia_tab.get_ui()
	local locked_notes = guide.locked_notes
	local unlocked_articles = xr_statistic.actor_articles
	if (locked_notes["encyclopedia__notes_" .. sec]) and (not unlocked_articles["encyclopedia__notes_" .. sec]) then
		dxr_encyclopedia.detect_note_interaction(sec)
		trx_utils.release_obj(obj)
	else
		SetHudMsg(game.translate_string("st_recipe_is_known"),3)
	end
	
	-- effect
	local hud = get_hud()
	if (hud) then
		hud:HideActorMenu()
	end
end

function use_letter(obj)
	local sec = obj:section()
	if not letter_tools[sec] then
		return
	end
	
	local guide = ui_pda_encyclopedia_tab.get_ui()
	local locked_notes = guide.locked_notes
	local unlocked_articles = xr_statistic.actor_articles
	if (locked_notes["encyclopedia__notes_" .. sec]) and (not unlocked_articles["encyclopedia__notes_" .. sec]) then
		dxr_encyclopedia.detect_note_interaction(sec)
		trx_utils.release_obj(obj)
	else
		SetHudMsg(game.translate_string("st_letter_is_known"),3)
	end
	
	-- effect
	local hud = get_hud()
	if (hud) then
		hud:HideActorMenu()
	end
end

function use_guitar(obj)
	local n = math.random(28)
	local snd = sound_object("music\\guitar_" .. tostring(n))
	if (not snd) then return end
	local period = snd:length()
	snd:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1)
	actor_effects.play_continuous_effect(period)
end

function use_harmonica(obj)
	local n = math.random(5)
	local snd = sound_object("music\\harmonica_" .. tostring(n))
	if (not snd) then return end
	local period = snd:length()
	snd:play_no_feedback(db.actor, sound_object.s2d, 0, vector(), 1)
	actor_effects.play_continuous_effect(period)
end

function use_arty_container(obj)
	local delay = 30
	local break_con
	local break_arty
	local sec = obj:section()
	--local con_o = level.object_by_id(obj:id())
	--local cond = con_o:condition()
	
	if (string.find(sec, "(lead.-_box)",3)) then
		break_con = "lead_box"
		break_arty = sec:gsub("_lead_box", "")		
	elseif (string.find(sec, "(af.-_iam)",3)) then
		break_con = "af_iam"
		break_arty = sec:gsub("_af_iam", "")
	elseif (string.find(sec, "(af.-_aac)",3)) then
		break_con = "af_aac"
		break_arty = sec:gsub("_af_aac", "")
	elseif (string.find(sec, "(af.-_aam)",3)) then
		break_con = "af_aam"
		break_arty = sec:gsub("_af_aam", "")
	end
	
	if break_con and break_arty and ini:section_exist(break_con) and ini:section_exist(break_arty) then
		trx_utils.create_inv_obj(break_con)
		trx_utils.create_inv_obj(break_arty)
		trx_utils.release_obj(obj)
		
		if (actor_effects.use_item(break_con .. "_dummy")) then
			actor_effects.use_item(break_con .. "_dummy")
			--level_weathers.get_weather_manager():forced_weather_change()
		end
		
		--[[ Carrying container's condition over the artefact
		-- Funnily enough, the new added item in inventory don't register quickly? so a timer is necessary
		local function timer()
			local arty = trx_utils.collect_inv_obj(break_arty , 0) or {}
			for i=1,#arty do
				local arty_o = level.object_by_id(arty[i]:id())
				if (arty_o:condition() > 0.99) then
					arty_o:set_condition(cond)
					break
				end
			end
			return true
		end
		CreateTimeEvent("container","delay",delay,timer)
		--]]
	end
end

function use_watch(obj)
	local Y, M, D, h, mint, sec, ms = game.get_game_time():get()
	local pharse = game.translate_string("st_dyn_news_day_part_am")
	if (h > 12) then
		h = 12 - h
		pharse = game.translate_string("st_dyn_news_day_part_pm")
	end
	
	trx_utils.hide_menu()
	SetHudMsg(tostring(h) .. ":" .. tostring(mint) .. " " .. pharse , 3)
end

function use_charger(obj)
	axr_battery.use_battery(obj)
end

--=======================================< Others >=======================================--

function check_actor_backpack()
	if (db.actor:has_info("actor_filled_backpack"))then
		return
	end

	local id = utils.load_var(db.actor,"actor_inv_backpack_id",nil)

	if not (id) then
		return
	end

	local se_obj = alife():object(id)
	if not (se_obj) then 
		return 
	end
	local st = db.storage[se_obj.id]
	local obj = st and st.object or level.object_by_id(id)

	if not (obj) then
		return
	end

	if (db.actor:has_info("actor_made_wish_for_riches")) then
		return 
	end
	
	local function itr_inv(temp,item)
		local id = item and item:section() ~= "itm_actor_backpack" and ActorBackPackKeep[item:section()] == nil and item:id()
		if (id and not is_ammo_for_wpn(item:section())) then
			local itm_slot
			local equipped
			for i=1,12 do
				if (i ~= 4) then
					itm_slot = db.actor:item_in_slot(i)
					if (itm_slot and itm_slot:id() == id) then
						equipped = true
						break
					end
				end
			end
			
			if (db.actor:is_on_belt(item)) then
				equipped = true
			end

			if (not equipped) then
				db.actor:transfer_item(item,obj)
			end
			equipped = nil
		end
	end

	db.actor:iterate_inventory(itr_inv)

	db.actor:give_info_portion("actor_filled_backpack")
end

function actor_on_trade(obj,sell_bye,money) -- bind_stalker on_trade

end

function actor_item_take(obj) -- bind_stalker on_item_take

end

function npc_on_item_take_from_box(npc,box,item)

end

function is_ammo_for_wpn(sec)
	local sim = alife()
	for i=2,3 do
		local wpn = db.actor:item_in_slot(i)
		if (wpn) then
			local ammos = alun_utils.parse_list(ini,wpn:section(),"ammo_class",true)
			if (ammos[sec]) then 
				return true 
			end
		end
	end
	return false
end

function loot_mutant(obj,clsid,t,npc,dont_create) -- Prepare mutant loot
	-- if not (db.actor) then 
	-- 	return 
	-- end 
	
	local clsid = clsid or obj and obj:clsid()
	if not (clsid) then
		return
	end

	local loot_table = alun_utils.collect_section(ini_mutant,clsid_to_section[clsid])

	local loot,sec
	for i=1,#loot_table do
		loot = alun_utils.str_explode(loot_table[i],",")
		if (loot and loot[1] and loot[2]) then
			if not (loot[3]) then
				loot[3] = 1
			end

			loot[2] = tonumber(loot[2])
			for i=1,loot[2] do
				if (math.random() <= tonumber(loot[3])) then
					--alun_utils.printf("loot_mutant: section=%s",loot[1])
					local se_obj
					if not dont_create then
						se_obj = alife():create(loot[1],npc and npc:position() or db.actor:position(),0,0,npc and npc:id() or 0)
					end
					if (t) then
						local item_section = loot[1]
						if not (t[item_section]) then
							t[item_section] = {}
						end
						t[item_section].count = t[item_section].count and t[item_section].count + 1 or 1
						if se_obj then t[item_section][t[item_section].count] = se_obj.id end
						--alun_utils.printf("loot_mutant")

						if npc and npc:id() ~= db.actor:id() then
							alife():create(loot[1],npc:position(),0,0,npc:id())
						end
					end
				end
			end
		end
	end
	
	-- Unlock relevant mutant article in guide.
	if (not npc) then
		dxr_encyclopedia.detect_mutant_interaction(clsid_to_section[clsid])
	end
end
--end of insertion